#!/bin/bash

####################################################
# @brief    Script for DMG-making OM
# 			Must be executed on m2375
# @author   Thibaut Carpentier

OM_VERSION="6.11"
APP_FOLDER="OM "$OM_VERSION
DMG_NAME="OM-"$OM_VERSION"-macOS"

create_simple_dmg()
{
	rm -rf _DMG
	mkdir _DMG
	cp -R "$APP_FOLDER" _DMG

	mkdir _DMG/Fonts/
	cp -R "$APP_FOLDER"/resources/fonts/mac/* _DMG/Fonts/
	#cp  INSTALL/backgroundImage.tiff _DMG_CONTENTS/.background
	#cp  INSTALL/DS_Store _DMG_CONTENTS/.DS_Store
	#ln -s /Applications/ _DMG_CONTENTS/Applications
	#ln -s /Library/Fonts/ _DMG_CONTENTS/Fonts
	
	hdiutil create -fs HFS+ -volname $DMG_NAME -srcfolder _DMG $DMG_NAME.dmg
	rm -rf _DMG
	
}



change_permission()
{
    # this function change the permission for a given folder
    # $1 : the folder
    echo "Setting permissions for $1"
    sudo chown -R root "$1"
    sudo chgrp -R admin "$1"
    sudo chmod -R o+rx "$1"
    sudo chmod -R ug+rwx "$1"
}

##########
### GO ###
##########

echo "***************************************************"
echo "Preparing DMG distribution for $APP_FOLDER"
echo "***************************************************"

rm -f $DMG_NAME.dmg

# change_permission "$APP_FOLDER"
create_simple_dmg


exit 0






