#!/bin/bash

# 32bits:
# LWARCH=32-bit
# LWEXEC=lispworks-7-0-0-x86-darwin

LWARCH=64-bit
LWVERSION=7.1
LWEXEC=lispworks-7-1-0-amd64-darwin

OM_VERSION="6.13"
APP_FOLDER="OM "$OM_VERSION
DMG_NAME="OM-"$OM_VERSION"-macOS"


deliver_app()
{
echo "***************************************************"
echo "COMPILING STANDALONE EXE"
echo "***************************************************"

	rm -rf ./OPENMUSIC/*.app/
	/Applications/LispWorks\ $LWVERSION\ \($LWARCH\)/LispWorks\ \($LWARCH\).app/Contents/MacOS/$LWEXEC -build ./OPENMUSIC/build/build-om/deliver.lisp
}


# deliver_app MUST have been called before..
pack_app()
{
echo "***************************************************"
echo "Packing $APP_FOLDER"
echo "***************************************************"

	cd ./OPENMUSIC/build/build-om/
	/Applications/LispWorks\ $LWVERSION\ \($LWARCH\)/LispWorks\ \($LWARCH\).app/Contents/MacOS/$LWEXEC -build pack-intel.lisp
	cd ../../..
	cp "README.txt" "$APP_FOLDER"
}

# pack_app MUST have been called before..
set_fonts()
{   
echo "***************************************************"
echo "Setting font resources in $APP_FOLDER"
echo "***************************************************"
   cp "$APP_FOLDER"/"$APP_FOLDER".app/Contents/Resources/fonts/mac/* "$APP_FOLDER"/"$APP_FOLDER".app/Contents/Resources/fonts/
   rm -rf "$APP_FOLDER"/"$APP_FOLDER".app/Contents/Resources/fonts/mac/
   rm -rf "$APP_FOLDER"/"$APP_FOLDER".app/Contents/Resources/fonts/win/
   rm -rf "$APP_FOLDER"/"$APP_FOLDER".app/Contents/Resources/fonts/linux/
	 	   
   cp "$APP_FOLDER"/"$APP_FOLDER".app/Contents/Info.plist .	   
   defaults write $(pwd)/Info.plist ATSApplicationFontsPath -string "fonts/"
   mv ./Info.plist "$APP_FOLDER"/"$APP_FOLDER".app/Contents/Info.plist
   chmod 644 "$APP_FOLDER"/"$APP_FOLDER".app/Contents/Info.plist
}

# pack_app MUST have been called before..
create_simple_dmg()
{
echo "***************************************************"
echo "Preparing DMG distribution for $APP_FOLDER"
echo "***************************************************"

	rm -f $DMG_NAME.dmg	
	#rm -rf _DMG
	#mkdir _DMG
	#cp -R "$APP_FOLDER" _DMG
	#ln -s /Applications/ _DMG/Applications
	#hdiutil create -fs HFS+ -volname $DMG_NAME -srcfolder _DMG $DMG_NAME.dmg
	hdiutil create -fs HFS+ -volname $DMG_NAME -srcfolder "$APP_FOLDER" $DMG_NAME.dmg
	#rm -rf _DMG	
}

zip_release()
{
	rm ./"$APP_FOLDER".zip
	zip -r ./"$APP_FOLDER".zip ./"$APP_FOLDER"/  
}

change_permission()
{
    # this function change the permission for a given folder
    # $1 : the folder
    echo "Setting permissions for $1"
    sudo chown -R root "$1"
    sudo chgrp -R admin "$1"
    sudo chmod -R o+rx "$1"
    sudo chmod -R ug+rwx "$1"
}

sign_release()
{
	./codesign-om6
}
#=============================
# MAIN SCRIPT
#=============================

if 	[ "$1" = "-d" ]; 	then 	deliver_app
elif	[ "$1" = "-p" ];	then	pack_app; set_fonts
elif	[ "$1" = "-dp" ];	then	deliver_app; pack_app; set_fonts
elif	[ "$1" = "-dmg" ];	then	create_simple_dmg
elif	[ "$1" = "-zip" ];	then	zip_release
elif	[ "$1" = "-sign" ];	then	sign_release	
elif	[ "$1" = "-dpd" ];	then	deliver_app; pack_app; set_fonts; create_simple_dmg
elif	[ "$1" = "-dpz" ];	then	deliver_app; pack_app; set_fonts; zip_release
elif	[ "$1" = "-all" ];	then	deliver_app; pack_app; set_fonts; sign_release; zip_release; create_simple_dmg
else 	
	echo "Dont'know what to do! :("	
	echo "Options:"
	echo "-d = deliver app"
	echo "-p = pack delivered app as a separate folder (including fonts) "
	echo "-dp = deliver and pack"
	echo "-sign = sign delivered package"
	echo "-zip = create ZIP from previously packed app"
	echo "-dmg = create DMG from previously packed app"
	echo "-dpd = deliver, pack and create DMG"
	echo "-dpz = deliver, pack and zip"
fi

exit 0






