#!/bin/bash

####################################################################
# @brief    Script for code-signing OM
# 			Must be executed on m2375
# @author   Thibaut Carpentier

OM_VERSION="6.11"

# location of the standalone
APP_NAME="OM 6.11_beta_0"

codesign -s WP9W99LHHP "$APP_NAME/resources/lib/mac/libportmidi.dylib" 
codesign -s WP9W99LHHP "$APP_NAME/resources/lib/mac/libsamplerate.dylib"
codesign -s WP9W99LHHP "$APP_NAME/resources/lib/mac/libsndfile.dylib"
codesign -s WP9W99LHHP "$APP_NAME/resources/lib/mac/OMJuceAudioLib.dylib"
codesign -s WP9W99LHHP "$APP_NAME/resources/lib/mac/SDIF.framework/Versions/3.11/SDIF"
codesign -s WP9W99LHHP "$APP_NAME/resources/lib/mac/SDIF.framework/"
codesign -s WP9W99LHHP "$APP_NAME/$APP_NAME.app"

# check code signing
codesign --verify --deep --strict --verbose=2 "$APP_NAME/$APP_NAME.app"

# check Gatekeeper
spctl -a -t exec -vv "$APP_NAME/$APP_NAME.app"