;;Hierarchical domains package
;;;
;;; By C. Rueda (c) IRCAM 921129
;;;
 
(defpackage "MARKED-DOMAINS"
  (:use "COMMON-LISP"  "DELAYED-EVAL")
  (:export "GET-LEFTMOST-IN-DOMAIN" "C-TREE-DOMAIN" "IN-DOMAIN?" "GET-VALUE"
           "SET-VALUE" "ASSERT-NOT-IN-DOMAIN" "GET-NODES-AT-DEPTH" "ALL-DOMAIN-OF"
           "SINGLETON-DOMAIN?" "FIRST-IN-DOMAIN" "FILTER-DOMAIN" "FATHER" "SUBTREES"
           "SINGLETON-INSTANCE?" "GET-CURRENT-INSTANCE" "NOT-IN-DOMAIN?"
           "GET-DOMAIN-ITEM" "SET-DOMAIN-ITEM" "COPY-ALL-TREE" "ALWAYS-TRUE"
           "COPY-DOMAIN-COLLECTION" "COPY-DOMAIN" "MAKE-TREE-DOMAIN" "FILTER-DEEP"
           "DO-TREE-DOMAIN" "NICELY-PUT" "NOT-NULL-DOMAIN?" "TREE-DATA"
           "GET-ALL-MARKS" "INVALIDATE-LEAF" "MARK" "GET-ALL-DOMAIN" 
           "REMOVE-FROM-DOMAIN" "SUBCOLLECTION" "GET-ROOT" "BETA-VALUE"
           "FILTER-LEAVES-DOMAIN" "GET-ONE-VALUE" "FORM-TREE-VALUES"))

(defpackage "SOFT-CONSTR"
  (:use "COMMON-LISP"  "MARKED-DOMAINS" "DELAYED-EVAL")
  (:export "SOFT-FORWARD-CHECK"
           "*ALL-SOLUTIONS*" "*DOMAINS*" "*DONE-FOR-USER*" "*NUM-VARS*"
           "NOT-NULL-SERIES"
           "*MAX-ADVANCE*" "ENABLED?" "*PROBLEM-CONSTRAINTS*" "ARC-CONSISTENCY"
           "HD-AC5-CONSISTENCY" "FULL-CONSISTENCY" "LOCAL-CONSISTENCY"
           "*BACKTRACK-TO*"))

(defpackage "HD-CONSTRAINTS"
  (:use "COMMON-LISP"  "SOFT-CONSTR" "MARKED-DOMAINS" "DELAYED-EVAL" "DELAYCONSTR")
  (:export "NECESSITY-DEGREE" "SATISFIED?"))
